version: '3'
services:
    postgres:
        image: 'postgres:latest'
        environment: 
            - POSTGRES_HOST_AUTH_METHOD=trust
    
    redis:
        image: 'redis:latest'
        environment:
            - REDIS_URL=redis://redis:6379

    jflask:
        build: .
        ports: 
            - "80:80"
        volumes:
            - .:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432