version: '3'
services:
    postgres:
        image: 'postgres:latest'
        environment: 
            - PGHOST=postgres
            - POSTGRES_HOST_AUTH_METHOD=trust
    
    redis:
        image: 'redis:latest'
        environment:
            - REDIS_URL=redis://redis:6379

    jflask:
        build: .
        ports: 
            - "80:80"
        volumes:
            - .:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres
            - PGPORT=5432
        depends_on:
            - "postgres"
    celery-beat:
        build: .
        command: celery beat -A run.celery --loglevel=INFO --pidfile=
        depends_on:
            - "redis"
            - "jflask"
    celery-worker:
        build: .
        command: celery worker -A run.celery --loglevel=INFO
        environment: 
            - PGHOST=postgres
        depends_on:
            - "postgres"
            - "redis"
            - "jflask"