version: '3'
services:
    postgres:
        image: 'postgres:latest'
        environment: 
            - POSTGRES_HOST=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=secret
    
    redis:
        image: 'redis:latest'
        environment:
            - REDIS_URL=redis://redis:6379

    jflask:
        build: .
        ports: 
            - "80:80"
        volumes:
            - .:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=secret
            - PGPORT=5432
    celery-beat:
        build: .
        command: celery beat -A run.celery --loglevel=INFO
        volumes:
            - .:/app
    celery-worker:
        build: .
        command: celery worker -A run.celery --loglevel=INFO
        volumes:
            - .:/app